# Generated by Django 4.0.4 on 2022-05-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_subscription_thumbnail_heights'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='ok', max_length=60),
            preserve_default=False,
        ),
    ]
