# Generated by Django 4.0.4 on 2022-05-30 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_image_temporarylink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarylink',
            name='file',
        ),
    ]
