# Generated by Django 4.0.4 on 2022-05-31 01:22

import django.core.validators
from django.db import migrations, models

import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_temporarylink_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=images.models.user_images_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
