# Generated by Django 4.0.4 on 2022-05-31 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarylink',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_links', to='images.image'),
        ),
        migrations.AlterField(
            model_name='temporarylink',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
